org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=/home/leon/.local/share/ModrinthApp/meta/java_versions/zulu17.66.19-ca-jre17.0.19-linux_x64

# Fabric Properties
minecraft_version=1.18.2
yarn_mappings=1.18.2+build.3
loader_version=0.14.19

# Mod Properties
maven_group=com.boatmod
archives_base_name=boatmod
mod_version=1.0.0

# Dependencies
fabric_api_version=0.76.0+1.18.2
